name: wise-geoguessr

services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: db
    restart: always
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.database
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: 'true'
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/sqlcmd/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  backend:
    container_name: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - '44303:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      # - SQLCONNSTR_DATABASE=Server=db;Database=wise-geoguessr;User Id=sa;Password=${MSSQL_SA_PASSWORD};Integrated Security=False;TrustServerCertificate=Yes;
  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - '5173:8080'
    environment:
      - API_HOST=backend
      - API_PORT=8080
