name: wise-geoguessr

services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: _db
    restart: always
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.database
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: 'true'
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/sqlcmd/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
