name: 🚀 Deploy to Prod

on:
  release:
    types: [published]

jobs:
  deploy-prod:
    name: Trigger Coolify prod deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          curl -X GET "${{ secrets.COOLIFY_URL }}?uuid=${{ secrets.COOLIFY_PROD_UUID }}&force=false" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"
